---
title: "About BC climate anomaly app"
author: "Aseem Sharma"
date: "`r paste('Date:', format(Sys.time(), '%d %B, %Y'))`"
output: html_document
---

### **The BC climate anomaly app**

#### **Background**

 The BC climate anomaly app aims to provide insights into climate variations within British Columbia (BC) and its sub-regions (eco-provinces and major watersheds). This tool facilitates the comparison of climate data against long-term averages and provides a visualization of the evolution of climate patterns over several decades since 1951. The application is updated on a monthly basis, providing climate change information with a lag of approximately two weeks.

 This application presents anomalies of fundamental climate parameters, specifically air temperature (minimum, maximum, and mean) and total precipitation. Users have the flexibility to select any of these climate parameters to observe spatial and temporal changes within their chosen region for specific month, season or year. The app generates spatial anomaly maps, climate normals and time series of anomalies along with a table of anomalies overview for the user selected inputs. Users can save the maps and plots generated by the application, obtain the full report in HTML format, and download associated data.

#### **Anomaly App page**

 The *Anomaly App* page, as a main application, presents the spatial anomalies maps, time series and trend of the anomalies, climate normals map and anomalies overview of the selected parameters for chosen period, months/seasons and region. The overview table shows average, minimum, and maximum anomalies within the specified region and period. Similarly, this page generates *time series* plots of anomalies for the selected region and parameter, spanning from 1951 to the present year. Additionally, it displays spatial plots of *climate normals*, indicating the average climatology (1981-2010) of the selected parameter. The climate normals map also shows the mean value and range of the anomaly. Users have the option to save maps, plots, and associated data.

#### **Download data and plot**

 By clicking the *Download Plot* button, users can save the plots with names that include the *region*, *parameter*, and *start and end years (or years of climate normal)* in *.PNG* format. The *Download Raster Data* button allows users to download spatial anomaly data and climate normal data in *GTiff* format for the selected region and period, with each band containing data for one year. The *Download anomaly time series data* button download spatially averaged time series of selected parameter anomalies for the chosen region in *.csv* format. The dataset includes four columns: year (*yr*), anomalies values (*ano*), parameter (*par*), month (*Mon*), and *region* (name of the region). For temperature-related parameters (*tmean*, *tmax*, or *tmin*), unit of anomaly is degrees Celsius **(°C)**, and for the precipitation (*prcp*), the unit is percentage of normal **(% of normal)**.
The anomaly data exclusively pertains to the landmass. Consequently, if there is no grid overlap between the landmass and the selected shapefile, the application will generate an error; reset the app to restore functional state.

 **Report** page provides a link to an HTML report providing a general overview spanning from 1980 to 2022 and month-to-month summaries for recent months and spatial anomalies and time series plots of monthly, seasonal, and annual anomalies.

 The BC climate anomaly app aims to provide insights into climate variations within British Columbia (BC) and its sub-regions (eco-provinces and major watersheds). This tool facilitates the comparison of climate data against long-term averages and provides a visualization of the evolution of climate patterns over several decades since 1951. The application is updated on a monthly basis, providing climate change information with a lag of approximately two weeks.

#### **Data and methods**

 The goal of this shiny app and the summary report is to help users understand how climate parameters have changed from long term average at monthly, seasonal and annual level in BC and sub regions. To achieve this, we use <a href='https://cds.climate.Copernicus.eu/cdsapp#!/data set/reanalysis-era5-land?tab=overview'> ERA5-Land hourly data</a> from the European Centre for Medium-Range Weather Forecasts (ERA5). The ERA5-Land is a reanalysis gridded data set developed combining model and observed data and is available at about 9 km by 9 km spatial and hourly temporal resolution.

 The anomaly of the variable is calculated relative to the 1981-2010 climatological normal (30-year average) of that variable. An anomaly for particular year or season or month is calculated by subtracting the climatological mean of the variable. The anomalies data are regridded to spatial resolution of about 30 km by 30 km.

 The Mann-Kendall test and the Theil-Sen trend estimate yield the significance and magnitude of the trend, for the period of 1950 to present year and 1980 to present year, respectively.

#### **Maintenance and continuity**

 This app is developed and maintained by Aseem R. Sharma <a href= 'mailto: Aseem.Sharma@gov.bc.ca'>Aseem.Sharma\@gov.bc.ca</a>, Research Climatologist at the <a href ='https://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resources-climate-change/future-forest-ecosystems-centre#:~:text=The%20Future%20Forest%20Ecosystems%20Centre%20(FFEC)%20was%20officially%20established%20in,on%20B.C.%27s%20forest%20ecosystems.'> Future Forest Ecosystems Center (FFEC) </a>, Forest Carbon and Climate Service Branch, Office of the Chief Forester, BC Ministry of Forests. Aseem R. Sharma and/or members of the FFEC team will maintain the app and ensure it is updated on a monthly basis to incorporate the latest data from the most recent month.

#### **Acknowledgements**

 We thank the European Centre for Medium-Range Weather Forecasts (ECMWF) for providing the ERA5-Land reanalysis via the Copernicus Climate Change Service.
